library imported


In [56]:
import pandas as pa
import numpy as np

fetching the iris dataset

In [57]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

just look what all data does data set is provided with and how they are arranged

In [58]:
print("iris_data set keys:\n{}".format(iris_dataset.keys()))

iris_data set keys:
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


lets look the 'DESCR' structure of the iris dataset 

In [59]:

print(iris_dataset['DESCR'][:500]+"\n..............................")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                

..............................


look what are in target_names

In [60]:
print('target_names : {}'.format(iris_dataset['target_names']))

target_names : ['setosa' 'versicolor' 'virginica']


lets look what feature_names holds

In [61]:
print('Featers_name: {}'.format(iris_dataset['feature_names']))

Featers_name: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


lets look what target holds

In [62]:
print('Target:\n{}'. format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


0-SETOSA,1-VERSICOLOR,2-VIRGINICA

lets look what first five data looks like

In [63]:
print('first five rows of data:\n {}'.format(iris_dataset['data'][:5]))

first five rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'

lets look the types

In [64]:
print('Type of the data: {}'.format(type(iris_dataset['data'])))

Type of the data: <class 'numpy.ndarray'>


In [65]:
print('type of target :{}'. format(type(iris_dataset['target'])))

type of target :<class 'numpy.ndarray'>


just verify the shape

In [66]:
print("shape of the data: {}".format(iris_dataset['data'].shape))

shape of the data: (150, 4)


In [67]:
print("shape of target : {}".format(iris_dataset['target'].shape))

shape of target : (150,)


teting the datasets

In [70]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'],iris_dataset['target'], random_state=0)

to just check the train and test data positions

In [71]:
print("X_train shape:{}".format(X_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("y_test shape:{}".format(y_test.shape))

X_train shape:(112, 4)
y_train shape:(112,)
X_test shape:(38, 4)
y_test shape:(38,)


just to make the model to make a kneighbour clasifier...

In [72]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [73]:
knn.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

now time to test the BOY

just see the shape of X_new

In [76]:
X_new = np.array([[5,2.9,1,0.2]])
print("X_new.shape:{}".format(X_new.shape))


X_new.shape:(1, 4)


lets see if he gusses correct

In [80]:
prediction = knn.predict(X_new)

print("Prediction:{}".format(prediction))
print("Predicted target name: {}".format(iris_dataset['target_names']
                                         [prediction]))

Prediction:[0]
Predicted target name: ['setosa']


evaluating


In [81]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [82]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158


 /

 /

 /

HERE IS MY VERTION OF ML

Machine to determine the type of flower if the inputs of sepal length,sepal width, petal length, petal width in CM is provided

In [86]:
import pandas as pa
import numpy as np

from sklearn.datasets import load_iris
iris_dataset = load_iris()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'],iris_dataset['target'], random_state=0)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(X_train, y_train)

print("provide the necessary information regarding the flower "
"in CM \nand i will tell you to which family they belong to \n")


X_new = np.array([[0.0,0.0,0.0,0.0]])
for i in range(0,4):
  if i == 0:
    X_new[0,i] = input("sepal length (cm) : ")
  if i == 1:
    X_new[0,i]  = input('sepal width (cm)  : ')
  if i == 2:
    X_new[0,i]  = input('petal length (cm) : ')
  if i == 3:
    X_new[0,i]  = input('petal width (cm)  : ')

prediction = knn.predict(X_new)

print(" \n From the given data it's a : {}".format(iris_dataset[
                                                        'target_names']
                                         [prediction]))

provide the necessary information regarding the flower in CM 
and i will tell you to which family they belong to 

sepal length (cm) : 5
sepal width (cm)  : 2.9
petal length (cm) : 1
petal width (cm)  : 0.2
 
 From the given data it's a : ['setosa']
